Module Dashboard - Estado erróneo de botón para actividad No Evaluable
leemonade/leemons pull request #104
Opened 2024-01-25 11:09 UTC by fermarinsanchez

If is no evaluabe, don't show "for evaluation" label

2024-01-25 12:45 UTC, MIGUELez11 requested changes
Remove log and fix sonarcloud

2024-01-25 12:45 UTC, MIGUELez11 commented on plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.js
> +  console.log('activity', activity);
Console.log :/

2024-01-25 16:50 UTC, fermarinsanchez commented on plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.js
> +  console.log('activity', activity);
@MIGUELez11 lo he visto en la rama que he creado después y lo he borrado. Podemos pasar este comment por alto.

2024-01-26 08:56 UTC, MIGUELez11 approved these changes

2024-01-26 08:58 UTC, merged