Sistemas de Evaluación - Deshabilitar borrado de SE si está en uso (edición)
leemonade/leemons pull request #320
Opened 2024-04-23 12:15 UTC by fermarinsanchez

fix(grades): Evaluation system - If a ES is in use, show drawer with all inputs and data on readonly/disabled mode.

2024-04-24 19:49 UTC, MIGUELez11 requested changes

2024-04-24 19:49 UTC, MIGUELez11 commented on plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/Scales.js
> +const Scales = ({ selectData, form, onBeforeRemove, inUse }) => {
Missing propTypes for inUse

2024-04-25 05:40 UTC, fermarinsanchez commented on plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/Scales.js
> +const Scales = ({ selectData, form, onBeforeRemove, inUse }) => {
solved.

2024-04-25 09:47 UTC, MIGUELez11 approved these changes

2024-04-25 09:48 UTC, merged