Unificar posición de Nombre y Apellidos y controlar espaciados
leemonade/leemons pull request #413
Opened 2024-05-17 07:34 UTC by fermarinsanchez

fix(calendar): parse calendar.name correctly if calendar is user calendar
fix(leebrary): delete Dimensions if asset is audio type. Add dependecies array to useMemo in Permissions data.

2024-05-24 16:03 UTC, MIGUELez11 requested changes

2024-05-24 16:03 UTC, MIGUELez11 commented on plugins/leemons-plugin-calendar/frontend/src/helpers/getCalendarNameWithConfigAndSession.js
> +    } ${session?.name}`;
Remove double space.

```suggestion
    label = `${session?.surnames !== null ? session?.surnames : ''}${
      session.surnames ? ', ' : ''
    }${session?.name}`;
```

2024-05-24 21:35 UTC, fermarinsanchez commented on plugins/leemons-plugin-calendar/frontend/src/helpers/getCalendarNameWithConfigAndSession.js
> +    } ${session?.name}`;
removed! thx!

2024-05-27 09:31 UTC, MIGUELez11 approved these changes

2024-05-27 09:32 UTC, merged