All assets - Vista previa - Armonización
leemonade/leemons pull request #451
Opened 2024-06-12 14:07 UTC by fermarinsanchez

Refactor and redesign previews of tasks, tests and surveys

2024-06-17 07:58 UTC, MIGUELez11 requested changes

2024-06-17 07:58 UTC, MIGUELez11 commented on plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/QuestionsCard.js
> +  // const moduleDashboardUrl = `/private/learning-paths/modules/dashboard/${moduleId}`;
Not used :D

```suggestion
```

2024-06-17 07:58 UTC, MIGUELez11 commented on plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Preview/index_old.js
File not used, maybe delete?

2024-06-17 07:58 UTC, MIGUELez11 commented on plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Detail.js
I would remove the commented code

2024-06-17 10:54 UTC, fermarinsanchez commented on plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/QuestionsCard.js
> +  // const moduleDashboardUrl = `/private/learning-paths/modules/dashboard/${moduleId}`;
Ok. done!

2024-06-17 10:54 UTC, fermarinsanchez commented on plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Preview/index_old.js
Ok. done!

2024-06-20 11:30 UTC, MIGUELez11 approved these changes

2024-06-20 13:59 UTC, MIGUELez11 approved these changes

2024-06-20 14:01 UTC, merged