Tarea: formato de archivo admitido en entregable se traspasa incorrectamente a Alumno
leemonade/leemons pull request #476
Opened 2024-06-19 06:39 UTC by fermarinsanchez

fix(tasks): Clean tags on onChange to keep extensions correctly typed.

2024-06-19 07:56 UTC, MIGUELez11 requested changes

2024-06-19 07:56 UTC, MIGUELez11 commented on plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Submissions/components/File/File.js
> +                extension.replace(/[ .]/g, '')
I would use `extension.trim()` as `.pdf` is accepted and the problem is with ` .pdf`
And I don't know if "double extensions" are official for mime: `.test.js`

2024-06-19 07:56 UTC, MIGUELez11 commented on plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Submissions/components/File/File.js
> +              console.log('validExtensions', validExtensions);
Log :D

```suggestion
```

2024-06-20 11:24 UTC, MIGUELez11 approved these changes

2024-06-20 12:10 UTC, fermarinsanchez commented on plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Submissions/components/File/File.js
> +              console.log('validExtensions', validExtensions);
Ups! :-)

2024-06-20 14:06 UTC, MIGUELez11 approved these changes

2024-06-20 14:06 UTC, merged