Reglas de test - Activar reglas de test en el drawer de asignación de módulos
leemonade/leemons pull request #481
Opened 2024-06-21 14:22 UTC by fermarinsanchez

In this task, when a user assign a module, on setup config , on tests assignation drawer, users can define rules, save as a preset this rules or select rules previously saved. 
Refactor on headers and question table.

2024-06-29 19:53 UTC, MIGUELez11 requested changes

2024-06-29 19:53 UTC, MIGUELez11 commented on plugins/leemons-plugin-tests/frontend/src/widgets/assignables/AssignmentDrawer.js
> +      addSuccessAlert('Config creada con éxito');
Translation required

2024-07-01 07:14 UTC, fermarinsanchez commented on plugins/leemons-plugin-tests/frontend/src/widgets/assignables/AssignmentDrawer.js
> +      addSuccessAlert('Config creada con éxito');
oh! ok! done!

2024-07-08 13:33 UTC, johan-fx approved these changes

2024-07-08 13:35 UTC, merged