Barra Total Layout en tarea y Test: empuja botones hacia la derecha
leemonade/leemons pull request #609
Opened 2024-10-22 11:31 UTC by fermarinsanchez

feat(assignables): ActivityHeader. Refactor on Delete, Archive and Close actions. Group all these actions in a Kebab menu to optimize spacing on ActivityHeader. Add new icons and translations.

2024-10-24 17:09 UTC, MIGUELez11 approved these changes

2024-10-24 17:13 UTC, MIGUELez11 requested changes
Remove the console.log

2024-10-25 06:06 UTC, fermarinsanchez commented on plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/components/CloseButtons_deprecated/CloseButtons.js
> +  console.log('instance', instance);
done!

2024-10-25 07:03 UTC, MIGUELez11 approved these changes

2024-10-25 07:05 UTC, merged